### PR TITLE
Update getting_started.html

### PR DESCRIPTION
**Pull request by begleysm**
- Fixed several lines of code whose old syntax threw errors
- Fixed several misspelled words

### CODE REVIEW

**Comment by jmmorato** [comment]
Thanks for your pull request but it should be merged here:

https://github.com/jmmorato/openddsharp/blob/develop/Documentation/OpenDDSharp.Standard.Doc/articles/getting_started.md

Feel free to create a PR in OpenDDSharp main project or I will adapt your changes there in my next documentation push.

**Comment by begleysm** [comment]
Thanks.  I created a PR for the correct project.

Will this update the webpage?  I suspect lots of people use the instructions at https://www.openddsharp.com/articles/getting_started.html.  Perhaps that page should simply redirect to https://github.com/jmmorato/openddsharp/blob/develop/Documentation/OpenDDSharp.Standard.Doc/articles/getting_started.md?

**Comment by jmmorato** [comment]
API documentation and Articles are auto-generated with docfx and then I push the web page to this repository. I plan to do it automatically with a documentation workflow from the main project but unfortunately I have not too much time for the project lately.

I will merge your changes and manually publish them here this afternoon when I finish my actual work day.

Thanks again for your help

**Comment by begleysm** [comment]
Roger!

You're welcome and thank you!

**Pull request closed without merging**
